[book]
title = "通过例子学 Rust"
description = "通过例子学 Rust, Rust By Example 中文版，RBE 中文版"
author = "Steve Klabnik and Carol Nichols, with Contributions from the Rust Community"
translator = "Aaran Xu"
language = "zh-CN"

[output.html]
additional-js = ["language.js"]
git-repository-url = "https://github.com/rust-lang-cn/rust-by-example-cn"
edit-url-template = "https://github.com/rust-lang-cn/rust-by-example-cn/edit/master/{path}"

[output.html.playpen]
editable = true
editor = "ace"
